language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-add misc/travis.php.ini; fi
  - composer install -o

sudo: false

services:
  - redis-server
